### ISSUE TITLE
Add Timer

### ISSUE THREAD

**Issue by xmha97** [matdlu/OneTimeAlarm#5]
Please add Timer (like the Google Clock)

**Comment by matdlu** [comment]
Can you post an screenshot of what you mean?

**Comment by xmha97** [comment]
![Screenshot_2022-11-20-19-09-04-304_com.google.android.deskclock.jpg](https://user-images.githubusercontent.com/23485114/202911274-8ae4d539-2047-4650-b5a6-14ac5b8f382d.jpg)
![Screenshot_2022-11-20-19-09-09-621_com.google.android.deskclock.jpg](https://user-images.githubusercontent.com/23485114/202911282-e6c295f3-d6ff-4149-b58f-c12ec6abf345.jpg)

**Comment by matdlu** [comment]
No, this is not this type of application. It just meant to do these simple alarms.
