### ISSUE TITLE
Set an alarm for every day

### ISSUE THREAD

**Issue by xmha97** [matdlu/OneTimeAlarm#6]
Hi, how can I set an alarm for every day?

**Comment by matdlu** [comment]
Hi, the whole idea of this app is to be able to set one time alarms, that is alarms that don't repeat. For repeating alarms like for every day You can use other applications like default clock app.

**Comment by xmha97** [comment]
I wanted you to add this feature.

**Comment by matdlu** [comment]
It's against the idea of this app
